Give cropped layers unique names
BiAPoL/napari-crop pull request #24
Opened 2022-05-24 17:13 UTC by zoccoler

Hi guys,

This Draft PR is intended to fix #20 .
The problem happened because after #7 because [here](https://github.com/BiAPoL/napari-crop/blob/86b9670fba2c00264cf0c7e68cda020fef06c2e3/napari_crop/_function.py#L104) we always assigned the same name for drawn shapes from the same Shapes layer, thus, napari replaces previous output Image layer data instead of creating a new layer if the function was executed again.

The proposed solution is to always provide a new unique name by checking layer names in the viewer (or layer names about to be added to the viewer in case of multiple shapes).

It works here. I will write a test before turning this into regular PR.

Best,
Marcelo

2022-05-24 17:33 UTC, zoccoler commented
I had to add the viewer as a new argument to the function.

Do you guys think this is OK for users using `crop_region` from code or should we make a wrapper function to keep it with the original arguments? @haesleinhuepf @tdmorello

2022-05-25 10:36 UTC, haesleinhuepf requested changes
Hi Marcelo @zoccoler ,

as discussed, the viewer should be optional. Furthermore, to ensure backwards-compatibility always add new parameters by the end of a parameter list and enter default values.

Otherwise great work. Thanks for working on this!

Best,
Robert

2022-05-25 10:36 UTC, haesleinhuepf commented on napari_crop/_tests/test_function.py
> +    cropped_actual = crop_region(viewer, img_layer, shapes_layer)
This change breaks backwards compatibility. If you added `viewer` as last parameter with default value `None`, it would be backwards-compatible

2022-05-25 10:36 UTC, haesleinhuepf commented on napari_crop/_function.py
>  ) -> List[LayerDataTuple]:
```suggestion
def crop_region(
    layer: napari.layers.Layer,
    shapes_layer: napari.layers.Shapes,
    viewer: 'napari.viewer.Viewer' = None, 
) -> List[LayerDataTuple]:
```
This should fix backwards compatibility

2022-05-25 10:36 UTC, haesleinhuepf commented on napari_crop/_function.py
> +    names_list = [layer.name for layer in viewer.layers]
As discussed, you may want to write an `if viewer == None:` statement here. In that case the function could still be used without having a viewer

2022-05-25 10:55 UTC, zoccoler commented on napari_crop/_tests/test_function.py
> +    cropped_actual = crop_region(viewer, img_layer, shapes_layer)
I agree

2022-05-25 14:51 UTC, zoccoler commented
Hi Robert @haesleinhuepf ,

I just implemented the changes. Tests pass locally. I also tested it manually a bit.
Please feel free to merge if you think it is ok.

Best,
Marcelo

2022-07-05 07:04 UTC, merged